import Navbar from './components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

// components

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const bodyStyle = {display: 'flex', justifyContent: 'center', marginTop: '40px', marginLeft: '40px', marginRight: '40px' }




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div style={bodyStyle} >
          {children}
        </div>
      </body>
    </html>
  )
}